version: '3'
services:
  mysql1:
    image: mysql:8.0
    container_name: mysql1
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - C:/mysql/data1:/var/lib/mysql
  mysql2:
    image: mysql:8.0
    container_name: mysql2
    ports:
      - 3307:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - C:/mysql/data2:/var/lib/mysql
