spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/active?useSSL=false
      username: root
      password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      format_sql: true
      use_sql_comments: true
    database: mysql
    open-in-view: false
inactive:
  hikari:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/inactive?useSSL=false
    username: root
    password: 1234
